background #090d16
foreground #f3e6bd

color8   #1b1d2b
color9   #b7374a
color10  #f3e6bd 
color11  #f3e6bd
color12  #f3e6bd
color13  #f3e6bd
color14  #f3e6bd
color15  #f3e6bd

color0   #040511
color1   #b7374a
color2   #f3e6bd
color3   #f3e6bd
color4   #f3e6bd
color5   #f3e6bd
color6   #2b3343
color7   #f3e6bd
