preload = /home/kitu/Downloads/wp16111697-minimalist-winter-night-sky-wallpapers.jpg

wallpaper {
	monitor  = HDMI-A-1
	path     = /home/kitu/Downloads/wp16111697-minimalist-winter-night-sky-wallpapers.jpg
	fit_mode = cover
}
